### ISSUE TITLE
Small Popup Module/Modal Not Abstracted Enough

### ISSUE THREAD

**Issue by MattMcLennan** [squad-up0/squadup#33]
In the small popup module, you have specific text that is for logout:

 <h3>Are you sure you wanna log out?</h3>

This can't be there if this component is an abstracted component which by the name implies that it is.

**Comment by kseebrinegar** [comment]
Ohh yeah. I forgot to use this component  as a  reusable component. The text  "Are you sure you wanna logout" will actually come as prop from the parent component. This component will be used in 4-5 other places on this application.  I just forgot to change that.
