### ISSUE TITLE
Change px to rem/em especially for font sizes

### ISSUE THREAD

**Issue by MattMcLennan** [squad-up0/squadup#34]
All pixels need to be changed to rem/em. Ideally all pixels should be changed to rem/em, although sometimes ppl still use px for 1 px spacing, anything else should really be ems/rems.

Also, why does base.scss have:

body {
    line-height: 1;
    background: white;
    height: 1000px;
}

**Comment by kseebrinegar** [comment]
Ohh yeah thats for testing purposes the 1000px; I just need some height and forgot to remove it.
